import Head from 'next/head'
// import Image from 'next/image'
import Link from "next/link"
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <img src="https://www.meltdigital.com/wp-content/uploads/2021/07/logo-white.svg" className="logo"/>
        <h1>React / SEO demo application</h1>
        <Link href="/" className="nav-link">Home</Link>
        <Link href="/page1" className="nav-link">Page 1</Link>
        <Link href="/page2" className="nav-link">Page 2</Link>
        <Link href="/page3" className="nav-link">Page 3</Link>
      </main>
    </>
  )
}
